name: Run peony.py

on:
  push:         # Trigger workflow on every push to the repository
    branches:
      - main    # Runs only when pushing to the 'main' branch
  schedule:     # Trigger workflow on a schedule (optional)
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run the Python script
    - name: Run peony.py
      run: python peony.py
